// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yefqxifcpzonvjlkovho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZnF4aWZjcHpvbnZqbGtvdmhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTAwNTIsImV4cCI6MjA3MDU4NjA1Mn0.tDHTQ3UOKnknOiM9b9zmz3zW3nt_X1LqLDikgL-NrIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});